version: '3.3'
services: 
    api:
        build: "."
        ports: 
            - "8080"
        restart: "always"
        networks: 
            - "api.network"
        deploy:
            replicas: 3
    nginx:
        image: "nginx:latest"
        depends_on:
            - api
        ports: 
            - "80:80"
        networks:
            - "api.network"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf:ro"
networks:
    api.network:
