name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd go-code; docker build . --file Dockerfile 
            --build-arg fbadmin=${{secrets.FBADMINSDK}} 
            --build-arg neo4jpass=${{secrets.NEO4J_DEV_PASS}}
            --tag repo.treescale.com/techster10173/ping_dev:latest
    
    -
      uses: docker/login-action@v1
      name: Login to Treescale
      with:
        registry: repo.treescale.com
        username: techster10173
        password: ${{secrets.TREESCALE_SREE_PASS}}
    
    - name: Push to Treescale
      run: docker push repo.treescale.com/techster10173/ping_dev:latest
    
    -
      uses: akhileshns/heroku-deploy@v3.12.12
      name: Deploy to Heroku
      with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: "ping-dev"
          heroku_email: "sreegrandhe@gmail.com"
          usedocker: true
          docker_build_args: |
            fbadmin
            neo4jpass
          env:
            fbadmin: ${{secrets.FBADMINSDK}}
            neo4jpass: ${{secrets.NEO4J_DEV_PASS}}

      
      
