name: Prod-Release CI

on:
  workflow_dispatch:

jobs:
  treescale_upload:
    name: Upload Docker Image to Treescale
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd go-code; docker build . --file Dockerfile.production 
            --build-arg fbadmin=${{ secrets.FBADMINSDK }} 
            --build-arg neo4jpass=${{ secrets.NEO4J_DEV_PASS }}
            --tag repo.treescale.com/techster10173/ping_prod:latest
    
    -
      uses: docker/login-action@v1
      name: Login to Treescale
      with:
        registry: repo.treescale.com
        username: techster10173
        password: ${{secrets.TREESCALE_SREE_PASS}}
    
    - name: Push to Treescale
      run: docker push repo.treescale.com/techster10173/ping_prod:latest
  
  heroku_upload:
    runs-on: ubuntu-latest
    needs: treescale_upload
    name: Upload Docker Image to Heroku
  
    steps:
      -
        uses: docker/login-action@v1
        name: Login to Treescale
        with:
          registry: repo.treescale.com
          username: techster10173
          password: ${{secrets.TREESCALE_SREE_PASS}}
      
      - name: Push to Treescale
        run: docker pull repo.treescale.com/techster10173/ping_prod:latest

      - name: Build Heroku Tag
        run: docker tag repo.treescale.com/techster10173/ping_prod:latest registry.heroku.com/ping-prod/web

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:login

      - name: Push to Heroku
        run: docker push registry.heroku.com/ping-prod/web

      - name: Release to Heroku
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_KEY }}
        run: heroku container:release web -a ping-prod
      
